// Code generated by generator/gen.go; DO NOT EDIT.
package lua

import (
	"github.com/ernmw/omwpacker/esm"
)

// VFS path to a Lua script.
const LUAS esm.SubrecordTag = "LUAS"

// VFS path to a Lua script.
type LUASField struct{ Value string }

func (t *LUASField) Tag() esm.SubrecordTag { return LUAS }

func (s *LUASField) Unmarshal(sub *esm.Subrecord) error {
	if s == nil || sub == nil {
		return esm.ErrArgumentNil
	}

	s.Value = string(sub.Data)

	return nil
}

func (s *LUASField) Marshal() (*esm.Subrecord, error) {
	if s == nil {
		return nil, nil
	}

	return &esm.Subrecord{Tag: s.Tag(), Data: []byte(s.Value)}, nil
}
